`/teachers`: alloted subjects are returned in the teachers list
Chirag4904/timetable pull request #20
Opened 2022-11-10 18:10 UTC by RoguedBear

2022-11-10 19:34 UTC, Chirag4904 requested changes
Able to get all teachers data correctly but not able to get data with queries like before.
Like http://localhost:5000/api/teachers is working fine but http://localhost:5000/api/teachers?id=1 which should return the teacher with id 1, is now returning null array.

2022-11-11 04:50 UTC, RoguedBear commented
I'll take a look at it. thnx

2022-11-13 14:18 UTC, RoguedBear commented
fixed it.
apparently it was happening because `id` was of the type `int` but input passed in from the query parameter was of type `string`.
even though mongooose typecasts the input automatically, it does not use that result in `$match` aggregate operator so we get a null result.

explicitly typecasting to integer if possible has fixed the issue (tho there is potential to improve this quick fix) in the teachers api and the subjects api as well

2022-11-14 06:34 UTC, Chirag4904 approved these changes

2022-11-14 06:36 UTC, merged